### ISSUE TITLE
Cannot invoke "java.io.File.isAbsolute()" because "f" is null

### ISSUE THREAD

**Issue by rgkirch** [nextjournal/clerk-demo#18]
I cloned `git@github.com:nextjournal/clerk-demo.git`
and then opened `clerk-demo/dev/user.clj` in emacs and ran `cider-jack-in-clj`.
I followed the instructions [here](https://snapshots.nextjournal.com/clerk/build/b12d8b369a69ca4b41fcf4988194dfbc201c6e1c/book.html).
```
[nREPL] Starting server via c\:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -encodedCommand YwBsAG8AagB1AHIAZQAgAC0AUwBkAGUAcABzACAAJwB7ADoAZABlAHAAcwAgAHsAbgByAGUAcABsAC8AbgByAGUAcABsACAAewA6AG0AdgBuAC8AdgBlAHIAcwBpAG8AbgAgACIAIgAwAC4AOQAuADAAIgAiAH0AIABjAGkAZABlAHIALwBjAGkAZABlAHIALQBuAHIAZQBwAGwAIAB7ADoAbQB2AG4ALwB2AGUAcgBzAGkAbwBuACAAIgAiADAALgAyADgALgA0ACIAIgB9ACAAYwBvAG0ALgBjAGUAbQBlAHIAaQBjAGsALwBwAG8AbQBlAGcAcgBhAG4AYQB0AGUAIAB7ADoAbQB2AG4ALwB2AGUAcgBzAGkAbwBuACAAIgAiADEALgAxAC4AMAAiACIAfQAgAHIAZQBmAGEAYwB0AG8AcgAtAG4AcgBlAHAAbAAvAHIAZQBmAGEAYwB0AG8AcgAtAG4AcgBlAHAAbAAgAHsAOgBtAHYAbgAvAHYAZQByAHMAaQBvAG4AIAAiACIAMwAuADUALgAyACIAIgB9AH0AIAA6AGEAbABpAGEAcwBlAHMAIAB7ADoAYwBpAGQAZQByAC8AbgByAGUAcABsACAAewA6AG0AYQBpAG4ALQBvAHAAdABzACAAWwAiACIALQBtACIAIgAgACIAIgBuAHIAZQBwAGwALgBjAG0AZABsAGkAbgBlACIAIgAgACIAIgAtAC0AbQBpAGQAZABsAGUAdwBhAHIAZQAiACIAIAAiACIAWwByAGUAZgBhAGMAdABvAHIALQBuAHIAZQBwAGwALgBtAGkAZABkAGwAZQB3AGEAcgBlAC8AdwByAGEAcAAtAHIAZQBmAGEAYwB0AG8AcgAsAGMAaQBkAGUAcgAuAG4AcgBlAHAAbAAvAGMAaQBkAGUAcgAtAG0AaQBkAGQAbABlAHcAYQByAGUAXQAiACIAXQB9AH0AfQAnACAALQBNADoAYwBpAGQAZQByAC8AbgByAGUAcABsAA==
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: #< CLIXML

Error building classpath. Cannot invoke "java.io.File.isAbsolute()" because "f" is null

java.lang.NullPointerException: Cannot invoke "java.io.File.isAbsolute()" because "f" is null

	at clojure.tools.deps.alpha.util.dir$canonicalize.invokeStatic(dir.clj:30)

	at clojure.tools.deps.alpha.extensions.deps$fn__1352.invokeStatic(deps.clj:32)

	at clojure.tools.deps.alpha.extensions.deps$fn__1352.invoke(deps.clj:32)

	at clojure.lang.MultiFn.invoke(MultiFn.java:244)

	at clojure.tools.deps.alpha$expand_deps$children_task__746$fn__748$fn__749.invoke(alpha.clj:406)

	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__479.invoke(concurrent.clj:34)

	at clojure.lang.AFn.call(AFn.java:18)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

	at java.base/java.lang.Thread.run(Thread.java:831)

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="3"><TNRef RefId="0" /><MS><I64 N="SourceId">3</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
error in process sentinel: Could not start nREPL server: #< CLIXML

Error building classpath. Cannot invoke "java.io.File.isAbsolute()" because "f" is null

java.lang.NullPointerException: Cannot invoke "java.io.File.isAbsolute()" because "f" is null

	at clojure.tools.deps.alpha.util.dir$canonicalize.invokeStatic(dir.clj:30)

	at clojure.tools.deps.alpha.extensions.deps$fn__1352.invokeStatic(deps.clj:32)

	at clojure.tools.deps.alpha.extensions.deps$fn__1352.invoke(deps.clj:32)

	at clojure.lang.MultiFn.invoke(MultiFn.java:244)

	at clojure.tools.deps.alpha$expand_deps$children_task__746$fn__748$fn__749.invoke(alpha.clj:406)

	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__479.invoke(concurrent.clj:34)

	at clojure.lang.AFn.call(AFn.java:18)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

	at java.base/java.lang.Thread.run(Thread.java:831)

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="3"><TNRef RefId="0" /><MS><I64 N="SourceId">3</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
```

[here's](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)Decode_text('UTF-16LE%20(1200)')&input=WXdCc0FHOEFhZ0IxQUhJQVpRQWdBQzBBVXdCa0FHVUFjQUJ6QUNBQUp3QjdBRG9BWkFCbEFIQUFjd0FnQUhzQWJnQnlBR1VBY0FCc0FDOEFiZ0J5QUdVQWNBQnNBQ0FBZXdBNkFHMEFkZ0J1QUM4QWRnQmxBSElBY3dCcEFHOEFiZ0FnQUNJQUlnQXdBQzRBT1FBdUFEQUFJZ0FpQUgwQUlBQmpBR2tBWkFCbEFISUFMd0JqQUdrQVpBQmxBSElBTFFCdUFISUFaUUJ3QUd3QUlBQjdBRG9BYlFCMkFHNEFMd0IyQUdVQWNnQnpBR2tBYndCdUFDQUFJZ0FpQURBQUxnQXlBRGdBTGdBMEFDSUFJZ0I5QUNBQVl3QnZBRzBBTGdCakFHVUFiUUJsQUhJQWFRQmpBR3NBTHdCd0FHOEFiUUJsQUdjQWNnQmhBRzRBWVFCMEFHVUFJQUI3QURvQWJRQjJBRzRBTHdCMkFHVUFjZ0J6QUdrQWJ3QnVBQ0FBSWdBaUFERUFMZ0F4QUM0QU1BQWlBQ0lBZlFBZ0FISUFaUUJtQUdFQVl3QjBBRzhBY2dBdEFHNEFjZ0JsQUhBQWJBQXZBSElBWlFCbUFHRUFZd0IwQUc4QWNnQXRBRzRBY2dCbEFIQUFiQUFnQUhzQU9nQnRBSFlBYmdBdkFIWUFaUUJ5QUhNQWFRQnZBRzRBSUFBaUFDSUFNd0F1QURVQUxnQXlBQ0lBSWdCOUFIMEFJQUE2QUdFQWJBQnBBR0VBY3dCbEFITUFJQUI3QURvQVl3QnBBR1FBWlFCeUFDOEFiZ0J5QUdVQWNBQnNBQ0FBZXdBNkFHMEFZUUJwQUc0QUxRQnZBSEFBZEFCekFDQUFXd0FpQUNJQUxRQnRBQ0lBSWdBZ0FDSUFJZ0J1QUhJQVpRQndBR3dBTGdCakFHMEFaQUJzQUdrQWJnQmxBQ0lBSWdBZ0FDSUFJZ0F0QUMwQWJRQnBBR1FBWkFCc0FHVUFkd0JoQUhJQVpRQWlBQ0lBSUFBaUFDSUFXd0J5QUdVQVpnQmhBR01BZEFCdkFISUFMUUJ1QUhJQVpRQndBR3dBTGdCdEFHa0FaQUJrQUd3QVpRQjNBR0VBY2dCbEFDOEFkd0J5QUdFQWNBQXRBSElBWlFCbUFHRUFZd0IwQUc4QWNnQXNBR01BYVFCa0FHVUFjZ0F1QUc0QWNnQmxBSEFBYkFBdkFHTUFhUUJrQUdVQWNnQXRBRzBBYVFCa0FHUUFiQUJsQUhjQVlRQnlBR1VBWFFBaUFDSUFYUUI5QUgwQWZRQW5BQ0FBTFFCTkFEb0FZd0JwQUdRQVpRQnlBQzhBYmdCeUFHVUFjQUJzQUE9PQ) the decoded command
```
clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version ""0.9.0""} cider/cider-nrepl {:mvn/version ""0.28.4""} com.cemerick/pomegranate {:mvn/version ""1.1.0""} refactor-nrepl/refactor-nrepl {:mvn/version ""3.5.2""}} :aliases {:cider/nrepl {:main-opts [""-m"" ""nrepl.cmdline"" ""--middleware"" ""[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]""]}}}' -M:cider/nrepl
```

**Comment by rgkirch** [comment]
I don't have this issue anymore.
